ConsoleLoggingEnabled = 1
FileLoggingEnabled = 1

#LogLevel
#From least significat bit to most significant
# LOG_LEVEL_INFO 		= 000001
# LOG_LEVEL_DEBUG 		= 000010
# LOG_LEVEL_OKSTATUS 		= 000100
# LOG_LEVEL_WARNING 		= 001000
# LOG_LEVEL_ERROR 		= 010000
# LOG_LEVEL_CRITICAL		= 100000

ConsoleLoggingLevel = 111111
FileLoggingLevel = 111111

# Client Version
CLIENT_VERSION_MAJOR = 1
CLIENT_VERSION_MINOR = 0
CLIENT_VERSION_REVISION = 0

# Server
NETWORK_THREADS_COUNT = 1
ASIO_THREADS_COUNT = 1

# MYSQL
LOGIN_DATABASE_URI = root:root@localhost:33060/necroauth
CHARACTERS_DATABASE_URI = root:root@localhost:33060/necrochars